[package]
name = "mc-launcher-core"
version = "0.0.1"
description = "todo"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
